#
# ~/.bashrc
#

# If not running interactively, don't do anything

#

#This should be it (all paths wanted in ${PATH} separated by colons) :
#export PATH="/usr/local/share/rsi/idl/bin:/home/username/anaconda/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local:$PATH"
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=10000

[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias psa="ps -A | grep"
alias p="pgrep -f"
alias startsowm="startx ~/.xinitrc sowm"
alias zzz="sleep 120m && systemctl suspend"
#PS1='[\u@\h \W]\$ '
PS1='$ '
